name: update_repo_secrets
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      
      - name: execute shell script 
        env:
         GH_TOKEN: ${{ secrets.PAT_VENU }}
        run: |
            chmod 755 GitHubSecretUpdate.sh
            sudo apt-get update
            sudo apt-get install dos2unix
            ./GitHubSecretUpdate.sh
        shell: bash
          
