name: Change Default Branch
description: Requesting for Change Default Branch
labels: ["Changedefaultbranch", "/approve-change"]

body:
  - type: markdown
    attributes:
      value: |
        Following fields are mandatory:
        - Repository Name*
        - Default Branch Name*                  
        
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this change default branch request!

  - type: input
    id: repository
    attributes:
      label: Repository Name
      description: Please provide the name of the repository.

  - type: input
    id: default_branch
    attributes:
      label: Default Branch Name
      description: Please provide the name of the default branch.
