name: Change Default Branch
about: Request to change the default branch of the repository
title: 'Change default branch'
labels: branch-change
assignees: 'POVENU'


### New Default Branch

Please specify the new default branch:

`new default branch: [branch-name]`
