name: Change Default Branch

on:
  issue_comment:
    types: [created]

jobs:
  approve-default-branch-change:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.issue.labels.*.name, 'change-default-branch') &&
      startsWith(github.event.comment.body, '/approve-change')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Parse new default branch from issue body
      id: parse_branch
      run: |
        echo "Parsing new default branch from issue body..."
        NEW_BRANCH=$(echo "${{ github.event.issue.body }}" | grep 'new-default-branch:' | sed 's/^.*new-default-branch: //' | xargs)
        echo "New default branch: $NEW_BRANCH"
        echo "new_default_branch=$NEW_BRANCH" >> $GITHUB_ENV

    - name: Change default branch
      if: success() && env.new_default_branch
      run: gh repo edit ${{ github.repository }} --default-branch ${{ env.new_default_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.VENU_TOKEN }}

    - name: Comment on issue
      run: |
        gh issue comment ${{ github.event.issue.number }} --body "Default branch has been changed to: ${{ env.new_default_branch }}"
      env:
        GITHUB_TOKEN: ${{ secrets.VENU_TOKEN }}
