name: Change Default Branch

on:
  push:
    branches:
      - main  # Adjust this as needed based on your current default branch
  workflow_dispatch:

jobs:
  change-default-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.VENU_TOKEN }}" | gh auth login --with-token

    - name: Change default branch
      run: gh repo edit {pogakve}/{screenshot_secrets} --default-branch test
      env:
        GITHUB_TOKEN: ${{ secrets.VENU_TOKEN }}
