name: Restore Repo Access
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: install go language
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install golang-go
          
      - name: Go Version
        run: go version

      - name: checkout repo content
        uses: actions/checkout@v2 
      
      - name: Restore Repo Access
        run: |
          cd RestoreRepoAccess/access
          go run access.go restore -c local.config.yml -ght "${{secrets.GHT}}" -ghr "$(cat ./testrepos.txt | sed -z 's|\n|,|g;s|,$|\n|')"
       # go run access.go restore -c local.config.yml -ght "$(cat ./.ght)" -ghr "wrs-api"
